
package com.tech.padawan.ServiceSoapToRest.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Data_Export", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", wsdlLocation = "http://3stecnologia.eti.br/data_export/data_export.asmx?wsdl")
public class DataExport
    extends Service
{

    private final static URL DATAEXPORT_WSDL_LOCATION;
    private final static WebServiceException DATAEXPORT_EXCEPTION;
    private final static QName DATAEXPORT_QNAME = new QName("http://servicos.3stecnologia.com.br/data_export", "Data_Export");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://3stecnologia.eti.br/data_export/data_export.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAEXPORT_WSDL_LOCATION = url;
        DATAEXPORT_EXCEPTION = e;
    }

    public DataExport() {
        super(__getWsdlLocation(), DATAEXPORT_QNAME);
    }

    public DataExport(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAEXPORT_QNAME, features);
    }

    public DataExport(URL wsdlLocation) {
        super(wsdlLocation, DATAEXPORT_QNAME);
    }

    public DataExport(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAEXPORT_QNAME, features);
    }

    public DataExport(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataExport(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataExportSoap
     */
    @WebEndpoint(name = "Data_ExportSoap")
    public DataExportSoap getDataExportSoap() {
        return super.getPort(new QName("http://servicos.3stecnologia.com.br/data_export", "Data_ExportSoap"), DataExportSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataExportSoap
     */
    @WebEndpoint(name = "Data_ExportSoap")
    public DataExportSoap getDataExportSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.3stecnologia.com.br/data_export", "Data_ExportSoap"), DataExportSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAEXPORT_EXCEPTION!= null) {
            throw DATAEXPORT_EXCEPTION;
        }
        return DATAEXPORT_WSDL_LOCATION;
    }

}
