
package com.tech.padawan.ServiceSoapToRest.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Data_ExportSoap", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataExportSoap {


    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidaLogin", action = "http://servicos.3stecnologia.com.br/data_export/ValidaLogin")
    @WebResult(name = "ValidaLoginResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ValidaLogin", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ValidaLogin")
    @ResponseWrapper(localName = "ValidaLoginResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ValidaLoginResponse")
    public String validaLogin(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha);

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaVeiculos", action = "http://servicos.3stecnologia.com.br/data_export/ListaVeiculos")
    @WebResult(name = "ListaVeiculosResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaVeiculos", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaVeiculos")
    @ResponseWrapper(localName = "ListaVeiculosResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaVeiculosResponse")
    public String listaVeiculos(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha);

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaClientes", action = "http://servicos.3stecnologia.com.br/data_export/ListaClientes")
    @WebResult(name = "ListaClientesResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaClientes", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaClientes")
    @ResponseWrapper(localName = "ListaClientesResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaClientesResponse")
    public String listaClientes(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha);

    /**
     * 
     * @param senha
     * @param idEquipamento
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaSensores", action = "http://servicos.3stecnologia.com.br/data_export/ListaSensores")
    @WebResult(name = "ListaSensoresResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaSensores", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaSensores")
    @ResponseWrapper(localName = "ListaSensoresResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaSensoresResponse")
    public String listaSensores(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param idEquipamento
     * @param usuario
     * @param dataInicio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaDistanciaVeiculo", action = "http://servicos.3stecnologia.com.br/data_export/RetornaDistanciaVeiculo")
    @WebResult(name = "RetornaDistanciaVeiculoResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaDistanciaVeiculo", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaDistanciaVeiculo")
    @ResponseWrapper(localName = "RetornaDistanciaVeiculoResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaDistanciaVeiculoResponse")
    public String retornaDistanciaVeiculo(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param usuario
     * @param dataInicio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaDistanciaVeiculos", action = "http://servicos.3stecnologia.com.br/data_export/RetornaDistanciaVeiculos")
    @WebResult(name = "RetornaDistanciaVeiculosResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaDistanciaVeiculos", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaDistanciaVeiculos")
    @ResponseWrapper(localName = "RetornaDistanciaVeiculosResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaDistanciaVeiculosResponse")
    public String retornaDistanciaVeiculos(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param idEquipamento
     * @param usuario
     * @param dataInicio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaUtilizacaoVeiculo", action = "http://servicos.3stecnologia.com.br/data_export/RetornaUtilizacaoVeiculo")
    @WebResult(name = "RetornaUtilizacaoVeiculoResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaUtilizacaoVeiculo", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaUtilizacaoVeiculo")
    @ResponseWrapper(localName = "RetornaUtilizacaoVeiculoResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaUtilizacaoVeiculoResponse")
    public String retornaUtilizacaoVeiculo(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param idEquipamento
     * @param usuario
     * @param dataInicio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HistoricoPosicao", action = "http://servicos.3stecnologia.com.br/data_export/HistoricoPosicao")
    @WebResult(name = "HistoricoPosicaoResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "HistoricoPosicao", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoPosicao")
    @ResponseWrapper(localName = "HistoricoPosicaoResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoPosicaoResponse")
    public String historicoPosicao(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param idEquipamento
     * @param usuario
     * @param dataInicio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HistoricoPosicaoCompleto", action = "http://servicos.3stecnologia.com.br/data_export/HistoricoPosicaoCompleto")
    @WebResult(name = "HistoricoPosicaoCompletoResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "HistoricoPosicaoCompleto", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoPosicaoCompleto")
    @ResponseWrapper(localName = "HistoricoPosicaoCompletoResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoPosicaoCompletoResponse")
    public String historicoPosicaoCompleto(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param idEquipamento
     * @param usuario
     * @param dataInicio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HistoricoTemperatura", action = "http://servicos.3stecnologia.com.br/data_export/HistoricoTemperatura")
    @WebResult(name = "HistoricoTemperaturaResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "HistoricoTemperatura", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoTemperatura")
    @ResponseWrapper(localName = "HistoricoTemperaturaResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoTemperaturaResponse")
    public String historicoTemperatura(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param idEquipamento
     * @param usuario
     * @param idSensor
     * @param dataInicio
     * @param blnLogradouro
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HistoricoSensor", action = "http://servicos.3stecnologia.com.br/data_export/HistoricoSensor")
    @WebResult(name = "HistoricoSensorResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "HistoricoSensor", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoSensor")
    @ResponseWrapper(localName = "HistoricoSensorResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoSensorResponse")
    public String historicoSensor(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim,
        @WebParam(name = "idSensor", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idSensor,
        @WebParam(name = "blnLogradouro", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String blnLogradouro);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param idEquipamento
     * @param usuario
     * @param idSensor
     * @param dataInicio
     * @param blnLogradouro
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HistoricoOcorrenciaSensor", action = "http://servicos.3stecnologia.com.br/data_export/HistoricoOcorrenciaSensor")
    @WebResult(name = "HistoricoOcorrenciaSensorResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "HistoricoOcorrenciaSensor", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoOcorrenciaSensor")
    @ResponseWrapper(localName = "HistoricoOcorrenciaSensorResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoOcorrenciaSensorResponse")
    public String historicoOcorrenciaSensor(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim,
        @WebParam(name = "idSensor", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idSensor,
        @WebParam(name = "blnLogradouro", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String blnLogradouro);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param idEquipamento
     * @param usuario
     * @param dataInicio
     * @param blnLogradouro
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HistoricoOcorrenciaVelocidade", action = "http://servicos.3stecnologia.com.br/data_export/HistoricoOcorrenciaVelocidade")
    @WebResult(name = "HistoricoOcorrenciaVelocidadeResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "HistoricoOcorrenciaVelocidade", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoOcorrenciaVelocidade")
    @ResponseWrapper(localName = "HistoricoOcorrenciaVelocidadeResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoOcorrenciaVelocidadeResponse")
    public String historicoOcorrenciaVelocidade(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim,
        @WebParam(name = "blnLogradouro", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String blnLogradouro);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param idEquipamento
     * @param usuario
     * @param dataInicio
     * @param blnLogradouro
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HistoricoOcorrenciaAlvo", action = "http://servicos.3stecnologia.com.br/data_export/HistoricoOcorrenciaAlvo")
    @WebResult(name = "HistoricoOcorrenciaAlvoResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "HistoricoOcorrenciaAlvo", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoOcorrenciaAlvo")
    @ResponseWrapper(localName = "HistoricoOcorrenciaAlvoResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoOcorrenciaAlvoResponse")
    public String historicoOcorrenciaAlvo(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim,
        @WebParam(name = "blnLogradouro", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String blnLogradouro);

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaUltimaPosicaoVeiculos", action = "http://servicos.3stecnologia.com.br/data_export/ListaUltimaPosicaoVeiculos")
    @WebResult(name = "ListaUltimaPosicaoVeiculosResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaUltimaPosicaoVeiculos", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaUltimaPosicaoVeiculos")
    @ResponseWrapper(localName = "ListaUltimaPosicaoVeiculosResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaUltimaPosicaoVeiculosResponse")
    public String listaUltimaPosicaoVeiculos(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha);

    /**
     * 
     * @param senha
     * @param idEquipamento
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaUltimaPosicaoVeiculo", action = "http://servicos.3stecnologia.com.br/data_export/ListaUltimaPosicaoVeiculo")
    @WebResult(name = "ListaUltimaPosicaoVeiculoResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaUltimaPosicaoVeiculo", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaUltimaPosicaoVeiculo")
    @ResponseWrapper(localName = "ListaUltimaPosicaoVeiculoResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaUltimaPosicaoVeiculoResponse")
    public String listaUltimaPosicaoVeiculo(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento);

    /**
     * 
     * @param senha
     * @param usuario
     * @param placa
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaUltimaPosicaoVeiculoPlaca", action = "http://servicos.3stecnologia.com.br/data_export/ListaUltimaPosicaoVeiculoPlaca")
    @WebResult(name = "ListaUltimaPosicaoVeiculoPlacaResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaUltimaPosicaoVeiculoPlaca", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaUltimaPosicaoVeiculoPlaca")
    @ResponseWrapper(localName = "ListaUltimaPosicaoVeiculoPlacaResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaUltimaPosicaoVeiculoPlacaResponse")
    public String listaUltimaPosicaoVeiculoPlaca(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "Placa", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String placa);

    /**
     * 
     * @param senha
     * @param data
     * @param idEquipamento
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaCoordenadaVeiculo", action = "http://servicos.3stecnologia.com.br/data_export/ListaCoordenadaVeiculo")
    @WebResult(name = "ListaCoordenadaVeiculoResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaCoordenadaVeiculo", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaCoordenadaVeiculo")
    @ResponseWrapper(localName = "ListaCoordenadaVeiculoResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaCoordenadaVeiculoResponse")
    public String listaCoordenadaVeiculo(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "Data", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String data);

    /**
     * 
     * @param idGateway
     * @param senha
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaDadosPosicao", action = "http://servicos.3stecnologia.com.br/data_export/RetornaDadosPosicao")
    @WebResult(name = "RetornaDadosPosicaoResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaDadosPosicao", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaDadosPosicao")
    @ResponseWrapper(localName = "RetornaDadosPosicaoResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaDadosPosicaoResponse")
    public String retornaDadosPosicao(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idGateway", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idGateway);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param idEquipamento
     * @param usuario
     * @param dataInicio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HistoricoMensagemEspecial", action = "http://servicos.3stecnologia.com.br/data_export/HistoricoMensagemEspecial")
    @WebResult(name = "HistoricoMensagemEspecialResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "HistoricoMensagemEspecial", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoMensagemEspecial")
    @ResponseWrapper(localName = "HistoricoMensagemEspecialResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoMensagemEspecialResponse")
    public String historicoMensagemEspecial(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim);

    /**
     * 
     * @param senha
     * @param dataFim
     * @param idEquipamento
     * @param usuario
     * @param dataInicio
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HistoricoMensagemTerminal", action = "http://servicos.3stecnologia.com.br/data_export/HistoricoMensagemTerminal")
    @WebResult(name = "HistoricoMensagemTerminalResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "HistoricoMensagemTerminal", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoMensagemTerminal")
    @ResponseWrapper(localName = "HistoricoMensagemTerminalResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.HistoricoMensagemTerminalResponse")
    public String historicoMensagemTerminal(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "DataInicio", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataInicio,
        @WebParam(name = "DataFim", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String dataFim);

    /**
     * 
     * @param senha
     * @param idEquipamento
     * @param blnTipoFormulario
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaFormularios", action = "http://servicos.3stecnologia.com.br/data_export/ListaFormularios")
    @WebResult(name = "ListaFormulariosResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaFormularios", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaFormularios")
    @ResponseWrapper(localName = "ListaFormulariosResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaFormulariosResponse")
    public String listaFormularios(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "blnTipoFormulario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String blnTipoFormulario);

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaFormulariosGrupo", action = "http://servicos.3stecnologia.com.br/data_export/ListaFormulariosGrupo")
    @WebResult(name = "ListaFormulariosGrupoResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaFormulariosGrupo", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaFormulariosGrupo")
    @ResponseWrapper(localName = "ListaFormulariosGrupoResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaFormulariosGrupoResponse")
    public String listaFormulariosGrupo(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha);

    /**
     * 
     * @param senha
     * @param usuario
     * @param idFormulario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaCamposFormulario", action = "http://servicos.3stecnologia.com.br/data_export/ListaCamposFormulario")
    @WebResult(name = "ListaCamposFormularioResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaCamposFormulario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaCamposFormulario")
    @ResponseWrapper(localName = "ListaCamposFormularioResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaCamposFormularioResponse")
    public String listaCamposFormulario(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idFormulario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idFormulario);

    /**
     * 
     * @param senha
     * @param idMensagem
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaDadosMensagemTerminal", action = "http://servicos.3stecnologia.com.br/data_export/RetornaDadosMensagemTerminal")
    @WebResult(name = "RetornaDadosMensagemTerminalResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaDadosMensagemTerminal", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaDadosMensagemTerminal")
    @ResponseWrapper(localName = "RetornaDadosMensagemTerminalResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaDadosMensagemTerminalResponse")
    public String retornaDadosMensagemTerminal(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idMensagem", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idMensagem);

    /**
     * 
     * @param senha
     * @param categoria
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaPOI", action = "http://servicos.3stecnologia.com.br/data_export/ListaPOI")
    @WebResult(name = "ListaPOIResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaPOI", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaPOI")
    @ResponseWrapper(localName = "ListaPOIResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaPOIResponse")
    public String listaPOI(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "Categoria", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String categoria);

    /**
     * 
     * @param senha
     * @param latitude
     * @param x
     * @param y
     * @param usuario
     * @param zoom
     * @param longitude
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaLinkMapa", action = "http://servicos.3stecnologia.com.br/data_export/RetornaLinkMapa")
    @WebResult(name = "RetornaLinkMapaResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaLinkMapa", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaLinkMapa")
    @ResponseWrapper(localName = "RetornaLinkMapaResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaLinkMapaResponse")
    public String retornaLinkMapa(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "Latitude", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        double latitude,
        @WebParam(name = "Longitude", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        double longitude,
        @WebParam(name = "X", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        int x,
        @WebParam(name = "Y", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        int y,
        @WebParam(name = "Zoom", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        int zoom);

    /**
     * 
     * @param senha
     * @param tipoStatus
     * @param idEquipamento
     * @param qtdeRegistro
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaStatusComunicacao", action = "http://servicos.3stecnologia.com.br/data_export/RetornaStatusComunicacao")
    @WebResult(name = "RetornaStatusComunicacaoResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaStatusComunicacao", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaStatusComunicacao")
    @ResponseWrapper(localName = "RetornaStatusComunicacaoResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaStatusComunicacaoResponse")
    public String retornaStatusComunicacao(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String idEquipamento,
        @WebParam(name = "TipoStatus", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String tipoStatus,
        @WebParam(name = "QtdeRegistro", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        int qtdeRegistro);

    /**
     * 
     * @param idAlertaMovimentacaoindevida
     * @param idAlertaSensor
     * @param idCercaCheckPoint
     * @param idEquipamento
     * @param idMensagem
     * @param idPosicao
     * @param idCercaRota
     * @param idAlertaTempoOperacaoContinua
     * @param senha
     * @param idAlertaTemperatura
     * @param idTelemetria
     * @param idAlertaJornadaDiaria
     * @param idCercaPoligonal
     * @param idAlertaVelocidade
     * @param usuario
     * @param idSensor
     * @param idCercaLogradouro
     * @param idCercaAlvo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaDados", action = "http://servicos.3stecnologia.com.br/data_export/RetornaDados")
    @WebResult(name = "RetornaDadosResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaDados", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaDados")
    @ResponseWrapper(localName = "RetornaDadosResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaDadosResponse")
    public String retornaDados(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idEquipamento", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idEquipamento,
        @WebParam(name = "idPosicao", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idPosicao,
        @WebParam(name = "idSensor", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idSensor,
        @WebParam(name = "idMensagem", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idMensagem,
        @WebParam(name = "idTelemetria", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idTelemetria,
        @WebParam(name = "idAlertaVelocidade", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idAlertaVelocidade,
        @WebParam(name = "idAlertaSensor", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idAlertaSensor,
        @WebParam(name = "idAlertaTemperatura", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idAlertaTemperatura,
        @WebParam(name = "idAlertaTempoOperacaoContinua", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idAlertaTempoOperacaoContinua,
        @WebParam(name = "idAlertaJornadaDiaria", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idAlertaJornadaDiaria,
        @WebParam(name = "idAlertaMovimentacaoindevida", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idAlertaMovimentacaoindevida,
        @WebParam(name = "idCercaAlvo", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idCercaAlvo,
        @WebParam(name = "idCercaCheckPoint", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idCercaCheckPoint,
        @WebParam(name = "idCercaLogradouro", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idCercaLogradouro,
        @WebParam(name = "idCercaPoligonal", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idCercaPoligonal,
        @WebParam(name = "idCercaRota", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idCercaRota);

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaGrupos", action = "http://servicos.3stecnologia.com.br/data_export/RetornaGrupos")
    @WebResult(name = "RetornaGruposResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaGrupos", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaGrupos")
    @ResponseWrapper(localName = "RetornaGruposResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaGruposResponse")
    public String retornaGrupos(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha);

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @param idComando
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaEnviosDeComandos", action = "http://servicos.3stecnologia.com.br/data_export/RetornaEnviosDeComandos")
    @WebResult(name = "RetornaEnviosDeComandosResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaEnviosDeComandos", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaEnviosDeComandos")
    @ResponseWrapper(localName = "RetornaEnviosDeComandosResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaEnviosDeComandosResponse")
    public String retornaEnviosDeComandos(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idVeiculo", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idVeiculo,
        @WebParam(name = "idComando", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idComando);

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaGruposFormularios", action = "http://servicos.3stecnologia.com.br/data_export/RetornaGruposFormularios")
    @WebResult(name = "RetornaGruposFormulariosResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaGruposFormularios", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaGruposFormularios")
    @ResponseWrapper(localName = "RetornaGruposFormulariosResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaGruposFormulariosResponse")
    public String retornaGruposFormularios(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha);

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @param idGrupo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornaGruposVeiculos", action = "http://servicos.3stecnologia.com.br/data_export/RetornaGruposVeiculos")
    @WebResult(name = "RetornaGruposVeiculosResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "RetornaGruposVeiculos", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaGruposVeiculos")
    @ResponseWrapper(localName = "RetornaGruposVeiculosResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.RetornaGruposVeiculosResponse")
    public String retornaGruposVeiculos(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "idGrupo", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idGrupo,
        @WebParam(name = "idVeiculo", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        long idVeiculo);

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SincronizaGrupoMacro", action = "http://servicos.3stecnologia.com.br/data_export/SincronizaGrupoMacro")
    @WebResult(name = "SincronizaGrupoMacroResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "SincronizaGrupoMacro", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.SincronizaGrupoMacro")
    @ResponseWrapper(localName = "SincronizaGrupoMacroResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.SincronizaGrupoMacroResponse")
    public String sincronizaGrupoMacro(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha);

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListaCercaRota", action = "http://servicos.3stecnologia.com.br/data_export/ListaCercaRota")
    @WebResult(name = "ListaCercaRotaResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ListaCercaRota", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaCercaRota")
    @ResponseWrapper(localName = "ListaCercaRotaResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ListaCercaRotaResponse")
    public String listaCercaRota(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha);

    /**
     * 
     * @param senha
     * @param usuario
     * @param operacoes
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConfiguraPainelRota", action = "http://servicos.3stecnologia.com.br/data_export/ConfiguraPainelRota")
    @WebResult(name = "ConfiguraPainelRotaResult", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
    @RequestWrapper(localName = "ConfiguraPainelRota", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ConfiguraPainelRota")
    @ResponseWrapper(localName = "ConfiguraPainelRotaResponse", targetNamespace = "http://servicos.3stecnologia.com.br/data_export", className = "com.tech.padawan.ServiceSoapToRest.wsdl.ConfiguraPainelRotaResponse")
    public String configuraPainelRota(
        @WebParam(name = "Usuario", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String senha,
        @WebParam(name = "Operacoes", targetNamespace = "http://servicos.3stecnologia.com.br/data_export")
        String operacoes);

}
